//! OpenAI-compatible tool/function calling types and extraction logic.

use serde::{Deserialize, Serialize};

use crate::model::chat_template::ChatMessage;

/// Tool definition in the request
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Tool {
    pub r#type: String,
    pub function: ToolFunction,
}

/// Function definition within a tool
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ToolFunction {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// A tool call generated by the model
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ToolCall {
    pub id: String,
    pub r#type: String,
    pub function: ToolCallFunction,
}

/// Function call details within a tool call
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ToolCallFunction {
    pub name: String,
    pub arguments: String,
}

/// Extended chat message for API request/response (supports tool_calls, tool_call_id)
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ChatRequestMessage {
    pub role: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Tool calls made by the assistant
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// ID of the tool call this message responds to (role=tool)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Function name (for role=tool messages)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Response message that can contain tool_calls
#[derive(Debug, Clone, Serialize)]
pub struct ChatResponseMessage {
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
}

/// Build a system prompt that describes available tools to the model.
pub fn build_tools_system_prompt(tools: &[Tool]) -> Option<String> {
    if tools.is_empty() {
        return None;
    }
    let mut prompt = String::from("You have access to the following tools:\n\n");
    for tool in tools {
        prompt.push_str(&format!("- {}", tool.function.name));
        if let Some(ref desc) = tool.function.description {
            prompt.push_str(&format!(": {}", desc));
        }
        prompt.push('\n');
        if let Some(ref params) = tool.function.parameters {
            if let Ok(json) = serde_json::to_string_pretty(params) {
                prompt.push_str(&format!("  Parameters: {}\n", json));
            }
        }
    }
    prompt.push_str(
        "\nTo call a tool, respond with: \
         <tool_call>{\"name\": \"function_name\", \"arguments\": {...}}</tool_call>",
    );
    Some(prompt)
}

/// Extract tool calls from model-generated text.
///
/// Models typically output tool calls as JSON in specific patterns.
/// Supports common formats:
/// 1. `<tool_call>{"name": "fn", "arguments": {...}}</tool_call>`
/// 2. `{"name": "fn", "arguments": {...}}` (bare JSON object with name+arguments keys)
pub fn extract_tool_calls(text: &str) -> (Option<String>, Option<Vec<ToolCall>>) {
    // Pattern 1: <tool_call>...</tool_call> tags
    let mut calls = Vec::new();
    let tag_start = "<tool_call>";
    let tag_end = "</tool_call>";

    if text.contains(tag_start) {
        let mut search = text;
        while let Some(start) = search.find(tag_start) {
            let after_tag = &search[start + tag_start.len()..];
            if let Some(end) = after_tag.find(tag_end) {
                let json_str = after_tag[..end].trim();
                if let Some(call) = parse_tool_call_json(json_str) {
                    calls.push(call);
                }
                search = &after_tag[end + tag_end.len()..];
            } else {
                break;
            }
        }
        if !calls.is_empty() {
            // Remove tool_call tags from content
            let remaining = text
                .split(tag_start)
                .next()
                .unwrap_or("")
                .trim()
                .to_string();
            let content = if remaining.is_empty() {
                None
            } else {
                Some(remaining)
            };
            return (content, Some(calls));
        }
    }

    // Pattern 2: Try to find a bare JSON object with "name" and "arguments" keys.
    // Scan backwards for each '{' and try parsing as a tool call.
    let mut search_from = text.len();
    while search_from > 0 {
        let prefix = &text[..search_from];
        let Some(start) = prefix.rfind('{') else {
            break;
        };
        let candidate = &text[start..];
        // Find matching closing brace
        let mut depth = 0;
        let mut end_pos = None;
        for (i, ch) in candidate.char_indices() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end_pos = Some(i + 1);
                        break;
                    }
                }
                _ => {}
            }
        }
        if let Some(end) = end_pos {
            let json_str = &candidate[..end];
            if let Some(call) = parse_tool_call_json(json_str) {
                let content_before = text[..start].trim();
                let content = if content_before.is_empty() {
                    None
                } else {
                    Some(content_before.to_string())
                };
                return (content, Some(vec![call]));
            }
        }
        search_from = start;
    }

    (Some(text.to_string()), None)
}

/// Parse a JSON string as a tool call
fn parse_tool_call_json(json_str: &str) -> Option<ToolCall> {
    let v: serde_json::Value = serde_json::from_str(json_str).ok()?;
    let obj = v.as_object()?;
    let name = obj.get("name")?.as_str()?;
    let arguments = obj.get("arguments")?;

    let args_str = if let Some(s) = arguments.as_str() {
        s.to_string()
    } else {
        serde_json::to_string(arguments).ok()?
    };

    Some(ToolCall {
        id: format!(
            "call_{}",
            &uuid::Uuid::new_v4().to_string().replace('-', "")[..24]
        ),
        r#type: "function".to_string(),
        function: ToolCallFunction {
            name: name.to_string(),
            arguments: args_str,
        },
    })
}

/// Convert ChatRequestMessage to ChatMessage for template formatting
pub fn request_msg_to_chat_msg(msg: &ChatRequestMessage) -> ChatMessage {
    let content = match msg.role.as_str() {
        "tool" => {
            // Format tool result: include the function name and result
            let name = msg.name.as_deref().unwrap_or("unknown");
            let content = msg.content.as_deref().unwrap_or("");
            format!("[Tool Result: {}]\n{}", name, content)
        }
        "assistant" if msg.tool_calls.is_some() => {
            // Format assistant tool calls as text for template
            let mut parts = Vec::new();
            if let Some(ref content) = msg.content {
                parts.push(content.clone());
            }
            if let Some(ref calls) = msg.tool_calls {
                for call in calls {
                    parts.push(format!(
                        "<tool_call>{{\"name\": \"{}\", \"arguments\": {}}}</tool_call>",
                        call.function.name, call.function.arguments
                    ));
                }
            }
            parts.join("\n")
        }
        _ => msg.content.clone().unwrap_or_default(),
    };

    ChatMessage {
        role: msg.role.clone(),
        content,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_tool_calls_tagged() {
        let text = r#"I'll look that up for you.
<tool_call>{"name": "get_weather", "arguments": {"city": "London"}}</tool_call>"#;
        let (content, calls) = extract_tool_calls(text);
        assert_eq!(content.as_deref(), Some("I'll look that up for you."));
        let calls = calls.unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "get_weather");
        assert_eq!(calls[0].r#type, "function");
        assert!(calls[0].function.arguments.contains("London"));
    }

    #[test]
    fn test_extract_tool_calls_multiple_tags() {
        let text = r#"<tool_call>{"name": "fn_a", "arguments": {}}</tool_call>
<tool_call>{"name": "fn_b", "arguments": {"x": 1}}</tool_call>"#;
        let (content, calls) = extract_tool_calls(text);
        let calls = calls.unwrap();
        assert_eq!(calls.len(), 2);
        assert_eq!(calls[0].function.name, "fn_a");
        assert_eq!(calls[1].function.name, "fn_b");
        // Content before first tag is empty
        assert!(content.is_none() || content.as_deref() == Some(""));
    }

    #[test]
    fn test_extract_tool_calls_bare_json() {
        let text = r#"Sure, let me check.
{"name": "search", "arguments": {"query": "rust lang"}}"#;
        let (content, calls) = extract_tool_calls(text);
        assert_eq!(content.as_deref(), Some("Sure, let me check."));
        let calls = calls.unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "search");
    }

    #[test]
    fn test_extract_tool_calls_no_tools() {
        let text = "Just a regular response with no tool calls.";
        let (content, calls) = extract_tool_calls(text);
        assert_eq!(content.as_deref(), Some(text));
        assert!(calls.is_none());
    }

    #[test]
    fn test_extract_tool_calls_invalid_json_ignored() {
        let text = r#"<tool_call>not valid json</tool_call>"#;
        let (content, calls) = extract_tool_calls(text);
        // Invalid JSON in tags → no calls extracted, falls through
        assert!(calls.is_none());
        assert!(content.is_some());
    }

    #[test]
    fn test_request_msg_to_chat_msg_tool_role() {
        let msg = ChatRequestMessage {
            role: "tool".to_string(),
            content: Some("{\"temp\": 20}".to_string()),
            tool_calls: None,
            tool_call_id: Some("call_abc".to_string()),
            name: Some("get_weather".to_string()),
        };
        let chat_msg = request_msg_to_chat_msg(&msg);
        assert_eq!(chat_msg.role, "tool");
        assert!(chat_msg.content.contains("[Tool Result: get_weather]"));
        assert!(chat_msg.content.contains("{\"temp\": 20}"));
    }

    #[test]
    fn test_request_msg_to_chat_msg_user() {
        let msg = ChatRequestMessage {
            role: "user".to_string(),
            content: Some("Hello".to_string()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        };
        let chat_msg = request_msg_to_chat_msg(&msg);
        assert_eq!(chat_msg.role, "user");
        assert_eq!(chat_msg.content, "Hello");
    }
}
